knownTriggers:
  "E2E Test Suites": "/run cluster-test-suites"
  "Release Test Suites": "/run releases-test-suites"

repos:
  cluster-test-suites:
    requiredChecks:
      - "E2E Test Suites"

  cluster-aws:
    requiredChecks:
      - "E2E Test Suites"
  cluster-eks:
    requiredChecks:
      - "E2E Test Suites"
  cluster-azure:
    requiredChecks:
      - "E2E Test Suites"
  cluster-gcp:
    requiredChecks:
      - "E2E Test Suites"
  cluster-cloud-director:
    requiredChecks:
      - "E2E Test Suites"
  cluster-vsphere:
    requiredChecks:
      - "E2E Test Suites"

  default-apps-aws:
    requiredChecks:
      - "E2E Test Suites"
  default-apps-azure:
    requiredChecks:
      - "E2E Test Suites"
  default-apps-gcp:
    requiredChecks:
      - "E2E Test Suites"
  default-apps-cloud-director:
    requiredChecks:
      - "E2E Test Suites"
  default-apps-vsphere:
    requiredChecks:
      - "E2E Test Suites"

  tinkerers-ci-test-1:
    requiredChecks:
      - "E2E Test Suites"
      - "Foo Bar"

  mc-bootstrap:
    requiredChecks:
      - "Generate MC - capa / goten"
      - "Generate MC - capz / goose"
      - "Generate MC - vsphere / gmc"
      - "Generate MC - cloud-director / goshawk"

  releases:
    requiredChecks:
      - "Release Test Suites"
